---
- name: Create symlinks for dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/
  with_items:
    - .agignore
    - .bash_aliases
    - .bashrc
    - .gitconfig
    - .gitignore
  tags:
    - dotfiles
