---
- name: Install other common GUI softwares
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - flameshot
    # Following package is responsible of starting autostart entries
    - gnome-tweaks
    - gnome-calculator
    - gnome-disk-utility
    - file-roller
    - nemo
    - keybase-gui
    - papirus-icon-theme
    # NTFS driver is needed to access external hard drives
    - ntfs-3g
    - xclip
  tags:
    - common-softwares

- name: Install common GUI softwares from AURs
  aur:
    name: "{{ item }}"
  with_items:
    # arandr is still simpler to use when doing presentations on
    # never-seen-before devices.
    - arandr
    - passwordsafe
    - spotify
  tags:
    - common-softwares

- name: Copy autostart config files
  copy:
    src: "archlinux/home/.config/autostart/"
    dest: "~/.config/autostart/"
  tags:
    - common-softwares
    - xinitrc

####################

- name: Install fonts from AURs
  aur:
    name: "{{ item }}"
  with_items:
    - nerd-fonts-complete
  tags:
    - common-softwares
    - fonts

- name: Install Powerline fonts
  become: yes
  package:
    name: "powerline-fonts"
  tags:
    - common-softwares
    - fonts

- name: Copy fontconfig config file
  copy:
    src: "archlinux/home/.config/fontconfig/"
    dest: "~/.config/fontconfig"
  tags:
    - common-softwares
    - fonts

####################

- name: Install Pulseaudio
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pulseaudio
    - pavucontrol
  tags:
    - common-softwares

####################

- name: Install softwares for (de)compression
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - p7zip
    - unzip
  tags:
    - common-softwares

####################

- name: Install Conky
  become: yes
  package:
    name: conky
    state: present
  tags:
    - common-softwares
    - conky

- name: Create Conky config directory
  file:
    path: ~/.config/conky
    state: directory
  tags:
    - common-softwares
    - conky

####################

- name: Install other common CLI tools
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tree
    - sysdig
    - pwgen
    - exa
    - bat
  tags:
    - common-softwares

####################

# To mount Android phones using MTP protocol
- name: Install gvfs-mtp
  become: yes
  package:
    name: "gvfs-mtp"
    state: present
  tags:
    - common-softwares

# Enable MTP automount
- name: Enable MTP automount
  become: yes
  lineinfile:
    path: /usr/share/gvfs/mounts/mtp.mount
    regexp: '^AutoMount='
    line: 'AutoMount=true'
  tags:
    - common-softwares
