---
- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  register: add_docker_repository
  tags:
    - docker

- name: Update APT cache
  become: yes
  apt:
    update_cache: yes
  when: add_docker_repository|changed
  tags:
    - docker

- name: Install docker
  become: yes
  package:
    name: docker-ce
    state: present
  tags:
    - docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: ~/bin/docker-compose
    mode: 0750
  tags:
    - docker

- name: Add current user to docker group
  become: yes
  command: "usermod -a -G docker {{ ansible_user_id }}"
  tags:
    - docker
